// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:ccd8832f-2ece-432d-917a-3f07fce03056",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_B6VCBWq0Q",
    "aws_user_pools_web_client_id": "62q3n32ngu1e3pjhpr1i1f0jfv",
    "oauth": {}
};


export default awsmobile;
