# This is a basic workflow to help you get started with Actions

name: Update_Dependencies

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
  - cron: "0 0 * * SUN"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v2
      
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout react/basic
        uses: actions/checkout@v2
        with:
          repository: ./react/basic
          path: react/basic
          
      - name: Checkout react/gqlNoRedux
        uses: actions/checkout@v2
        with:
          repository: ./react/gqlNoRedux
          path: react/gqlNoRedux

      # Runs a single command using the runners shell
      - name: "initiating update script"
        run: echo -e "\033[0;34m info \033[0m initiating update script..."

      # Runs a set of commands using the runners shell
      - name: "running commands"
        run: |
          echo -e "\033[0;34m info \033[0m running commands..."
          echo -e "\033[0;34m info \033[0m checking for yarn..."
          yarn -v
          if [ $? == 0 ]; then
            echo -e "\033[0;34m info \033[0m running yarn upgrade..."
            yarn upgrade
          else
            echo -e "\033[0;31m err \033[0m yarn not found..."
            echo -e "\033[0;34m info \033[0m running npm update..."
            npm update
          fi
          
          if [ $? == 0 ]; then
            git add .
            echo -e "\033[0;34m info \033[0m creating a commit..."
            git commit . -m "updated dependencies"
            if [ $? != 1 ]; then
              echo -e "\033[0;34m info \033[0m pushing to master..."
              git push origin master
              
            else
              echo -e "\033[0;34m info \033[0m repo is already up to date."
            fi
          else
            echo -e "\033[0;31m err \033[0m something went wrong, unable to upgrade."
          fi
          
              
